#!/usr/bin/env bash

manual_acceptance_items() {
  cat <<'EOF'
install_identity	Install identity and privacy stability	Install /Applications/Delta.app, launch it, quit, relaunch, and confirm macOS privacy prompts remain stable across rebuilds signed by the same identity.
settings_surface	Settings surface	Confirm Settings shows plain-language Scheduled Backups status, not raw LaunchAgent or implementation status; the compact status summary matches Full Disk Access, schedules, Pause automatic runs, Password Access, updates, notifications, idle-sleep protection, and bundled backup-tool state; expand How Scheduled Backups Work and confirm it explains closed-window scheduling, macOS approval, user-level permissions, and policy checks without raw implementation status; Password Access exposes status, refresh, and Repair Password Access; Run Due Now uses the same rules as automatic scheduled runs when they are not paused; Open Activity jumps to live and saved job output for scheduled-run troubleshooting; Start at Login uses macOS Login Items separately from scheduled backups; when Time Machine system support and Scheduled Backups both need Login Items attention, confirm the System Access card shows exactly one Review Login Items action; Sparkle automatic checks and background downloads are configurable; reset buttons restore recommended backup and restore defaults; new-profile schedule defaults are configurable and seed new profiles without rewriting existing ones; backup freshness warnings, source-access warnings, destination-check warnings, local/mounted destination free-space warnings, and activity history retention are configurable or visible where appropriate.
full_disk_access	Full Disk Access	From Settings, open Privacy & Security, add Delta manually when required, recheck access, and confirm the dashboard only shows Readiness when action is needed. With access off, confirm a Time Machine Connect action routes to Permissions before FSKit, DiskImages, or remote writes begin; with access on, confirm the exact installed app/helper arrangement can add and remove the verified destination through public `tmutil`.
scheduled_backups	Scheduled Backups	Confirm the automated scheduler acceptance report passed, then create an enabled scheduled profile in the UI, approve Delta in Login Items if macOS asks, turn on Pause automatic runs and confirm due runs do not start, resume automatic runs, quit the main window, wait for the scheduler interval, and confirm the scheduled run appears in Dashboard, Activity, and menu bar state after relaunch.
password_access	Password access	Use an app-managed destination and a destination with backend credentials. Confirm Settings and diagnostics show Password Access as Ready, then confirm a scheduled backup does not show interactive Keychain prompts after Repair Password Access has been run when needed.
local_drive_destination	Local or external drive destination	Create a new local or external-drive destination, confirm automatic preparation runs, then run a first backup and a second no-change backup.
mounted_network_drive	Mounted SMB or NFS destination	Test at least one SMB or NFS mounted path under /Volumes, disconnect it, confirm Delta reports destination unavailable without invoking restic, reconnect it, and confirm backup resumes. Also test an unwritable mounted destination and confirm Delta fails the write probe before invoking restic.
sftp_destination	SFTP destination	Test a real SFTP destination with a non-root absolute path and non-interactive SSH authentication through a configured key file or ssh-agent; confirm wrong credential/key failure, corrected credential success, restore point refresh, and restore.
s3_destination	S3-compatible destination	Test at least one S3-compatible provider with endpoint, bucket, optional region, missing credential failure, corrected credential success, backup, check, and restore.
remote_backend_matrix	Additional restic remote backends	Test REST server, Backblaze B2, Azure Blob, Google Cloud Storage, OpenStack Swift, rclone, and custom restic URL destinations with provider-specific credentials/configuration; confirm backup, check, restore point refresh, selected restore, cleanup, and post-cleanup check.
time_machine_format	Time Machine format	Using the exact stable-signed installed candidate and an isolated disposable remote store, open System Settings → General → Login Items & Extensions. Under Extensions, choose **By Category**. Click the info button beside **File System Extensions**, enable **Delta Time Machine Storage**, and confirm Delta's Permissions page updates to Allowed. Approve Background Items, prove enabled system support is not accepted until the exact installed helper returns its authenticated readiness identity, create and connect a disk whose cache is smaller than its capacity, and confirm macOS identifies the case-sensitive APFS Backup volume and exact Time Machine destination. Complete first, no-change, and changed backups; browse and restore full and selected data; verify restored bytes; disconnect, relaunch, reconnect, and recover after removing local configuration. Measure cache and memory bounds, prove no complete sparsebundle or band payload is retained locally, exercise provider loss, upload and manifest faults, lease contention, cancellation, forced unmount, update re-registration, helper launch failure, partial-mount cleanup, and safe removal, and confirm every uncertain outcome fails without false connection, backup, or eject success. Repeat the remote lifecycle against the genuine provider families required for release evidence and exercise the native UI with keyboard and VoiceOver.
remote_first_backup_preparation	Remote first-backup preparation	Add a new unprepared remote destination, start a backup without pressing Prepare first, and confirm Delta probes, prepares when missing, then runs the backup. Repeat with an existing remote destination and confirm Delta reuses it without reinitializing.
restore_wizard	Restore wizard	Test full restore, selected folder restore from the browser, selected file restore, dry-run preview, chosen-folder restore, original-path preview, original-path confirmation, and every overwrite policy.
restore_defaults	Restore defaults	Change Settings > Restore Defaults, reopen Restore, and confirm preview, verification, and overwrite policy defaults apply while remaining editable per restore.
new_backup_defaults	New backup defaults	Change Settings > New Backup Defaults, create a new profile, and confirm schedule enabled/cadence, catch-up, battery, Low Power Mode, bandwidth, retention keep rules, prune, post-cleanup check, and cleanup cadence defaults are applied while existing profiles remain unchanged. Confirm Health Monitoring thresholds change dashboard attention timing, destination-check timing, and local/mounted destination free-space warnings without mutating profiles.
browse_restore_points	Browse restore points	Confirm restore points load when the Restore tab is selected, refresh returns all current points, pruned points disappear after cleanup, and newest points are listed first.
pause_resume_cancel	Pause, resume, and cancel	Start a large backup, pause it from the main app and menu bar, confirm the profile stays paused with Resume visible, resume it, then cancel a separate run and confirm it is not resumable.
streaming_logs	Streaming and saved logs	With a large saved history, confirm Activity opens immediately, the run list scrolls smoothly, warning runs open in grouped issue review, omitted-item count excludes restic's aggregate warning, nested restic causes and paths are visible, exact and recommended exclusions require confirmation and affect only future runs, an all-acknowledged repeat run appears as Completed with known omissions and leaves Needs Attention while preserving its raw exit code and issues, any new or changed issue restores warning attention, All Output loads a bounded newest page, Earlier prepends the next stable page without duplicates, source context remains visible, and a running job can append output without resetting the selected run.
menu_bar	Menu bar status item and persistent popover	Confirm the native status item appears when enabled, hides when disabled, changes icon for ready, running, and attention states, and keeps its popover open while a backup transitions from running to completed. Confirm Back Up Now, Run Due Backups, Pause, Stop, Activity, Updates, and last-backup status work from the popover.
notifications	Notifications	Enable job alerts in Settings, allow macOS notification permission, use Send Test Alert, trigger one warning or failed job from the app and one scheduled job, and confirm successful-backup summaries only appear when the separate success setting is enabled.
sparkle_update_install	Sparkle update install	Install an older signed build, host or publish a signed appcast and archive, check for updates, install the update, and confirm settings, Full Disk Access identity, destinations, profiles, restore points, and scheduled behavior remain intact.
diagnostics_redaction	Diagnostics export redaction	Copy and export a diagnostic report and confirm it contains app, scheduler, tool, profile, and job state but no destination password or backend credential values.
developer_id_notarization	Developer ID notarization	For release builds only, sign with Developer ID, submit for notarization, staple the ticket, verify Gatekeeper launch, and archive notarization logs.
EOF
}
