#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_PATH="${1:-${DELTA_ACCEPTANCE_APP:-/Applications/Delta.app}}"
OUTPUT_DIR="${DELTA_DIAGNOSTICS_ACCEPTANCE_DIR:-$ROOT_DIR/dist/local-acceptance}"
SECRET="super-secret-diagnostic-value"

if [[ ! -d "$APP_PATH" ]]; then
  printf "Delta app bundle not found at %s\n" "$APP_PATH" >&2
  exit 1
fi

DELTA_EXECUTABLE="$APP_PATH/Contents/MacOS/Delta"
if [[ ! -x "$DELTA_EXECUTABLE" ]]; then
  printf "Delta executable is missing or not executable: %s\n" "$DELTA_EXECUTABLE" >&2
  exit 1
fi

INFO_PLIST="$APP_PATH/Contents/Info.plist"

plist_value() {
  local key="$1"
  /usr/libexec/PlistBuddy -c "Print :$key" "$INFO_PLIST" 2>/dev/null || printf "Unknown"
}

/bin/mkdir -p "$OUTPUT_DIR"
TIMESTAMP="$(/bin/date -u +%Y%m%dT%H%M%SZ)"
OUTPUT="$OUTPUT_DIR/Delta-installed-diagnostics-$TIMESTAMP.md"
LATEST="$OUTPUT_DIR/installed-diagnostics-latest.md"
WORK_DIR="$(/usr/bin/mktemp -d -t delta-installed-diagnostics.XXXXXX)"
SUPPORT_DIR="$WORK_DIR/support"
REPORT_FILE="$WORK_DIR/diagnostics.md"
SEED_LOG="$WORK_DIR/seed.log"
trap '/bin/rm -rf "$WORK_DIR"' EXIT

cat >"$OUTPUT" <<EOF
# Delta Installed Diagnostics Acceptance

- Generated: $TIMESTAMP UTC
- App: $APP_PATH
- Bundle ID: $(plist_value CFBundleIdentifier)
- Version: $(plist_value CFBundleShortVersionString)
- Build: $(plist_value CFBundleVersion)
- Git Commit: $(/usr/bin/git -C "$ROOT_DIR" rev-parse --short HEAD 2>/dev/null || printf "unknown")

This seeds isolated Application Support data through the installed Delta app, exports the installed app's diagnostic report, and verifies backup destination secrets and backend credential values are redacted.

EOF

DELTA_ENABLE_DIAGNOSTIC_ACCEPTANCE=1 \
DELTA_APP_SUPPORT_DIR="$SUPPORT_DIR" \
  "$DELTA_EXECUTABLE" --acceptance-seed-diagnostics >"$SEED_LOG" 2>&1

DELTA_APP_SUPPORT_DIR="$SUPPORT_DIR" \
  "$DELTA_EXECUTABLE" --export-diagnostics >"$REPORT_FILE" 2>"$WORK_DIR/export.stderr"

if [[ -s "$WORK_DIR/export.stderr" ]]; then
  {
    printf "## Export Stderr Was Not Empty\n\n"
    printf '```text\n'
    /bin/cat "$WORK_DIR/export.stderr"
    printf '```\n'
  } >>"$OUTPUT"
  printf "Installed diagnostics acceptance failed. See %s\n" "$OUTPUT" >&2
  exit 1
fi

required_patterns=(
  "# Delta Diagnostic Report"
  "- Profiles: 1"
  "- Destinations: 1"
  "- Restore Points: 1"
  "- Recent Jobs: 1"
  "rest:https://<redacted>@example.com/repo"
  "AWS_SECRET_ACCESS_KEY=<redacted>"
)

for pattern in "${required_patterns[@]}"; do
  if ! /usr/bin/grep -Fq -- "$pattern" "$REPORT_FILE"; then
    {
      printf "## Missing Expected Diagnostic Evidence\n\n"
      printf "Missing pattern: %s\n\n" "$pattern"
      printf '```text\n'
      /bin/cat "$REPORT_FILE"
      printf '```\n'
    } >>"$OUTPUT"
    printf "Installed diagnostics acceptance failed. See %s\n" "$OUTPUT" >&2
    exit 1
  fi
done

if /usr/bin/grep -Fq -- "$SECRET" "$REPORT_FILE"; then
  {
    printf "## Secret Redaction Failed\n\n"
    printf "The diagnostic report contained the seeded secret value.\n\n"
    printf '```text\n'
    /bin/cat "$REPORT_FILE"
    printf '```\n'
  } >>"$OUTPUT"
  printf "Installed diagnostics acceptance failed. See %s\n" "$OUTPUT" >&2
  exit 1
fi

cat >>"$OUTPUT" <<EOF
## Result

Installed diagnostics acceptance passed.

- Diagnostic report generated by installed app: Yes
- Isolated Application Support used: Yes
- Destination and profile counts from installed app state: Yes
- Seeded destination URL credential redacted: Yes
- Seeded backend credential value redacted: Yes
- Seeded secret value absent from report: Yes

## Seed Output

\`\`\`text
$(/bin/cat "$SEED_LOG")
\`\`\`

## Diagnostic Excerpt

\`\`\`text
$(/usr/bin/sed -n '1,120p' "$REPORT_FILE")
\`\`\`
EOF

LATEST_TMP="$OUTPUT_DIR/.installed-diagnostics-latest.$$"
/bin/ln -s "$(basename "$OUTPUT")" "$LATEST_TMP"
/bin/mv -f "$LATEST_TMP" "$LATEST"

printf "Wrote installed diagnostics acceptance to %s\n" "$OUTPUT"
printf "Updated %s\n" "$LATEST"
printf "Installed diagnostics acceptance passed for %s\n" "$APP_PATH"
